FROM golang:1.18 as builder

RUN mkdir /app

WORKDIR /app

COPY . .

WORKDIR /app/hello

RUN go mod init hello

RUN go build

FROM scratch

COPY --from=builder /app /

WORKDIR /hello

ENTRYPOINT ["./hello"]